spring:
  application:
    name: penny-pilot
  profiles:
    active: prod
  banner:
    location: classpath:banner.txt

  # Database connection
  datasource:
    url: jdbc:mysql://localhost:3306/money_manager_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA & Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${BREVO_USERNAME}
    password: ${BREVO_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 5353
  servlet:
    context-path: /api/v1.0/

email:
  activation:
    endpoint: ${EMAIL_ACTIVATION_ENDPOINT}

penny:
  pilot:
    backend:
      url: ${PENNY_PILOT_BACKEND_URL}
    frontend:
      url: ${PENNY_PILOT_FRONTEND_URL}